cat > local.yaml <<LOCALRUN
AZURE_TENANT_ID: "${TENANT_ID}"
AZURE_CLIENT_ID: "${ENV_PRINCIPAL_ID}"
AZURE_CLIENT_SECRET: "${ENV_PRINCIPAL_SECRET}"
azure_activedirectory_session_stateless: "true"
azure_activedirectory_AppIdUri: "api://${ENV_APP_ID}"
aad_client_id: "${ENV_APP_ID}"
appinsights_key: "${ENV_APPINSIGHTS_KEY}"
KEYVAULT_URI: "${ENV_KEYVAULT}"
cosmosdb_database: "${COSMOS_DB_NAME}"
storage_account: "${ENV_STORAGE}"
azure_storage_container_name: "${LEGAL_STORAGE_CONTAINER}"
azure_storage_enable_https: "true"
servicebus_topic_name: "${LEGAL_SERVICE_BUS_TOPIC}"
servicebus_namespace_name: "${ENV_SERVICEBUS_NAMESPACE}"
entitlements_service_endpoint: "https://${ENV_HOST}/entitlements/v1"
entitlements_service_api_key: "${API_KEY}"
LOG_PREFIX: "legal"
legal_service_region: "us"
server_port: "${server_port}"
LOCALRUN

cat > test/local.yaml <<LOCALTEST
HOST_URL: "http://localhost:${server_port}/api/legal/v1/"
ENTITLEMENT_URL: "https://${ENV_HOST}/entitlements/v1/"
MY_TENANT: "${OSDU_TENANT}"
AZURE_AD_TENANT_ID: "${TENANT_ID}"
INTEGRATION_TESTER: "${ENV_PRINCIPAL_ID}"
AZURE_TESTER_SERVICEPRINCIPAL_SECRET: "${ENV_PRINCIPAL_SECRET}"
AZURE_AD_APP_RESOURCE_ID: "${ENV_APP_ID}"
AZURE_LEGAL_STORAGE_ACCOUNT: "${ENV_STORAGE}"
AZURE_LEGAL_STORAGE_KEY: "${ENV_STORAGE_KEY}"
AZURE_LEGAL_SERVICEBUS: "${ENV_SERVICEBUS_CONNECTION}"
AZURE_LEGAL_TOPICNAME: "${LEGAL_SERVICE_BUS_TOPIC}"
LOCALTEST

cat > test/hosted.yaml <<DEVTEST
HOST_URL: "https://${ENV_HOST}/api/legal/v1/"
ENTITLEMENT_URL: "https://${ENV_HOST}/entitlements/v1/"
MY_TENANT: "${OSDU_TENANT}"
AZURE_AD_TENANT_ID: "${TENANT_ID}"
INTEGRATION_TESTER: "${ENV_PRINCIPAL_ID}"
AZURE_TESTER_SERVICEPRINCIPAL_SECRET: "${ENV_PRINCIPAL_SECRET}"
AZURE_AD_APP_RESOURCE_ID: "${ENV_APP_ID}"
AZURE_LEGAL_STORAGE_ACCOUNT: "${ENV_STORAGE}"
AZURE_LEGAL_STORAGE_KEY: "${ENV_STORAGE_KEY}"
AZURE_LEGAL_SERVICEBUS: "${ENV_SERVICEBUS_CONNECTION}"
AZURE_LEGAL_TOPICNAME: "${LEGAL_SERVICE_BUS_TOPIC}"
DEVTEST
