#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

#####################
# README: Defines an common build stage that any external app service pipeline can call into.
#####################

parameters:
  serviceBase: ''
  copyFileContentsToFlatten: ''
  copyFileContents: ''
  mavenGoal: 'clean package'
  serviceCoreMavenGoal: 'install'
  serviceCoreMavenOptions: ''
  sonarServiceConnection: ''
  testingRootFolder: 'testing/integration-tests'
  mavenPomFile: 'pom.xml'
  mavenPublishJUnitResults: false
  mavenOptions: ''
  checkoutRepo: self
  cacheVersion: 'service-dependency-cache-v0.1'

stages:

- stage: 'Build'
  variables:
    artifactName: 'drop'

  jobs:
  - job: Build_Test_Copy_Publish
    displayName: Perform Maven build and unit test / code coverage
    # Using Microsoft Hosted Agent Pool with Ubuntu 18.04 as it contains JDK 8 as default
    pool:
      vmImage: $(AGENT_IMAGE)
    workspace:
      clean: all
    steps:
    - download: none
    - checkout: ${{ parameters.checkoutRepo }}
      persistCredentials: true

    - task: Cache@2
      inputs:
        key: 'maven | "${{ parameters.cacheVersion }}" | "$(Agent.OS)" | **/pom.xml'
        restoreKeys: |
          maven | "${{ parameters.cacheVersion }}" | "$(Agent.OS)"
          maven | "${{ parameters.cacheVersion }}"
        path: $(Pipeline.Workspace)/.m2/repository
      displayName: Cache Maven local repo

    - task: Maven@3
      displayName: 'Maven: validate'
      inputs:
        mavenPomFile: ${{ parameters.mavenPomFile }}
        goals: 'validate'

    - task: SonarQubePrepare@4
      displayName: 'Prepare analysis on SonarQube'
      condition: and(succeeded(), ne('${{ parameters.sonarServiceConnection }}', ''))
      inputs:
        SonarQube: ${{ parameters.sonarServiceConnection }}
        scannerMode: Other
        extraProperties: |
          sonar.projectKey=${{ parameters.sonarProjectKey }}
          sonar.coverage.jacoco.xmlReportPaths=${{ parameters.sonarReportPaths }}

    - task: Maven@3
      displayName: 'Maven Core Build'
      condition: ne('${{ parameters.serviceCoreMavenOptions }}', '')
      inputs:
        mavenPomFile: ${{ parameters.mavenPomFile }}
        options: ${{ parameters.serviceCoreMavenOptions }}
        goals: ${{ parameters.serviceCoreMavenGoal }}
        publishJUnitResults: ${{ parameters.mavenPublishJUnitResults }}

    - task: Maven@3
      displayName: 'Maven Build'
      inputs:
        mavenPomFile: ${{ parameters.mavenPomFile }}
        options: ${{ parameters.mavenOptions }}
        goals: ${{ parameters.mavenGoal }}
        publishJUnitResults: ${{ parameters.mavenPublishJUnitResults }}

    - task: ArchiveFiles@2
      displayName: 'Archive integration tests'
      inputs:
        rootFolderOrFile: ${{ parameters.testingRootFolder }}
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.serviceBase }}-integration-tests.zip
        replaceExistingArchive: true

    - task: CopyFiles@2
      condition: ne('${{ parameters.copyFileContentsToFlatten }}', '')
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder:
        Contents: ${{ parameters.copyFileContentsToFlatten }}
        TargetFolder: '$(build.artifactstagingdirectory)'
        flattenFolders: true

    - task: CopyFiles@2
      displayName: 'Copy artifacts for maven deploy to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder:
        Contents: ${{ parameters.copyFileContents }}
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ${{ variables.artifactName }}'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: '${{ variables.artifactName }}'
        publishLocation: 'Container'
      condition: succeededOrFailed()
