version: '3'
services:
  probetest:
    build:
      context: .
      dockerfile: Dockerfile
    image: msosdu.azurecr.io/osdu-probe:$VERSION
    environment:
      TERM: xterm
      TENANT_ID: $TENANT_ID
      PRINCIPAL_ID: $PRINCIPAL_ID
      PRINCIPAL_SECRET: $PRINCIPAL_SECRET
      CLIENT_ID: $CLIENT_ID
      SUBSCRIPTION_ID: $SUBSCRIPTION_ID
      OSDU_HOST: $OSDU_HOST
      APPINSIGHTS_INSTRUMENTATIONKEY: $APPINSIGHTS_INSTRUMENTATIONKEY
      VERSION: $VERSION
