apiVersion: v1
kind: Service
metadata:
  name: osdu-common
  namespace: osdu
  labels:
    app: osdu-common
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: osdu-common
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-common
  namespace: osdu
spec:
  selector:
    matchLabels:
      app: osdu-common
  replicas: 1
  template:
    metadata:
      labels:
        app: osdu-common
    spec:
      containers:
        - name: osdu-common
          image: neilpeterson/aks-helloworld:v1
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "Azure OSDU Platform - (AKS)"
