{{- $isEnabled := .Values.global.isDataPartitionDeployment | default false -}}
{{ if and $isEnabled .Values.global.ingress.enableKeyvaultCert }}
apiVersion: apps/v1
kind: Deployment
metadata:
  # This Deployment is needed to download the certificate from keyvault via csi provider
  name: byoc-certificate-downloader
  namespace: istio-system
  labels:
    app: byoc-certificate-downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byoc-certificate-downloader
  template:
    metadata:
      labels:
        app: byoc-certificate-downloader
        aadpodidbinding: "osdu-identity"
    spec:
      containers:
      - name: byoc-certificate-downloader
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: osdu-tls
          mountPath: "/mnt/osdu-tls"
          readOnly: true
        env:
        - name: TLS_KEY
          valueFrom:
            secretKeyRef:
              name: osdu-certificate
              key: tls.key
      volumes:
      - name: osdu-tls
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: osdu-tls  
{{ end }}