{{- $isEnabled := .Values.global.isDataPartitionDeployment | default false -}}
{{ if and $isEnabled .Values.global.ingress.enableKeyvaultCert }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: osdu-tls
  namespace: istio-system
spec:
  provider: azure
  secretObjects:
  - secretName: osdu-certificate
    type: kubernetes.io/tls
    data: 
    - objectName: istio-ssl-certificate
      key: tls.key
    - objectName: istio-ssl-certificate
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    resourceGroup: "{{ .Values.global.azure.dp.resourcegroup }}"
    keyvaultName: "{{ .Values.global.azure.dp.keyvault }}"
    subscriptionId: "{{ .Values.global.azure.dp.subscription }}"
    tenantId: "{{ .Values.global.azure.dp.tenant }}"
    objects: |
      array:
        - |
          objectName: istio-ssl-certificate
          objectType: secret
{{ end }}