{{- $isEnabled := .Values.global.isDataPartitionDeployment | default false -}}
{{ if and $isEnabled (not .Values.global.ingress.enableKeyvaultCert) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: istio-system
spec:
  acme:
    email: {{ .Values.global.ingress.admin }}
    privateKeySecretRef:
      name: letsencrypt
    server: {{ .Values.global.ingress.sslServer }}
    solvers:
    - http01:
        ingress:
          class: istio
{{ end }}