#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /charts/airflow2/*
      - /source/airflow-function/*
    exclude:
      - /**/*.md

pr:
  autoCancel: false
  branches:
    include:
      - "*"
    exclude:
      - master
  paths:
    include:
      - /charts/airflow2/*
      - /source/airflow-function/*
    exclude:
      - /**/*.md

variables:
  - group: 'Azure - OSDU'
  - group: 'Azure - OSDU secrets'

  - name: airflowServiceName
    value: "airflow2"
  - name: airflowChartPath
    value: "charts/airflow2"
  - name: airflowValuesFile
    value: "charts/airflow2/helm-config-dp.yaml"
  - name: istioServiceName
    value: "istio"
  - name: istioChartPath
    value: "charts/osdu-istio"
  - name: istioValuesFile
    value: "charts/helm-config-dp.yaml"
  - name: podOperatorNamespace
    value: "airflow"

stages:
  - template: pipeline-stages/airflow-custom-stages.yml
    parameters:
      sourceFolder: "source"
      #multiple file paths to be provided with pipe(|) seperated
      dockerFilePaths: "airflow-function|airflow-statsd"
      baseResourceGroupName: $(base-name-dp)
      podOperatorNamespace: ${{ variables.podOperatorNamespace }}
      providers:
        - name: Azure
          environments: ["dev", "glab"]

  - template: /devops/chart-stages-dp.yml
    parameters:
      serviceName: ${{ variables.istioServiceName }}
      chartPath: ${{ variables.istioChartPath }}
      valuesFile: ${{ variables.istioValuesFile }}
      skipDeploy: ${{ variables.SKIP_DEPLOY }}
      DPName: "opendes"
      addDPNameToService: false
      providers:
        - name: Azure
          environments: ["dev", "glab"]

  - template: /devops/chart-stages-dp.yml
    parameters:
      serviceName: ${{ variables.airflowServiceName }}
      chartPath: ${{ variables.airflowChartPath }}
      valuesFile: ${{ variables.airflowValuesFile }}
      skipDeploy: ${{ variables.SKIP_DEPLOY }}
      namespace: airflow2
      DPName: "opendes"
      addDPNameToService: true
      providers:
        - name: Azure
          environments: ["dev", "glab"]
