#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /charts/airflow2/*
    exclude:
      - /**/*.md

variables:
  - group: "Azure - OSDU"
  - group: "Azure - OSDU secrets"

  - name: serviceName
    value: "airflow2"
  - name: chartPath
    value: "charts/airflow2"
  - name: valuesFile
    value: "charts/airflow2/helm-config.yaml"
  - name: podOperatorNamespace
    value: "airflow"

stages:
  - template: /charts/airflow2/pipeline-stages/airflow-custom-stages.yml
    parameters:
      sourceFolder: "source"
      #multiple file paths to be provided with pipe(|) seperated
      dockerFilePaths: "airflow-function|airflow-statsd"
      baseResourceGroupName: $(base-name-sr)
      podOperatorNamespace: ${{ variables.podOperatorNamespace }}
      providers:
        - name: Azure
          environments: ["demo"]

  - template: /devops/chart-stages-helm.yml
    parameters:
      serviceName: ${{ variables.serviceName }}
      chartPath: ${{ variables.chartPath }}
      valuesFile: ${{ variables.valuesFile }}
      skipDeploy: ${{ variables.SKIP_DEPLOY }}
      skipCheck: true
      # Add multiple chart folder paths with pipe(|) seperated
      extractedChartFolder: "templates|charts/airflow/templates"
      baseResourceGroupName: $(base-name-sr)
      namespace: "airflow2"
      providers:
        - name: Azure
          environments: ["demo"]
