
cat > .env <<EOF
REGISTRY=${REGISTRY}
VSTS_FEED_TOKEN=${VSTS_FEED_TOKEN}
SUBSCRIPTION_NAME=${ENV_SUBSCRIPTION_NAME}
STORAGE_CONNECTION_STRING=${ENV_STORAGE_CONNECTION}
SERVICE_BUS_ENDPOINT=${ENV_SERVICEBUS_CONNECTION}
TOPIC_NAME=${RECORD_SERVICE_BUS_TOPIC}
EOF
