FROM node:lts-buster

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/appinsights-statsd
COPY . /usr/src/app/appinsights-statsd

WORKDIR /usr/src/app

# Install python
# RUN apk add --no-cache --update g++ gcc libgcc libstdc++ linux-headers make python

# Install dependencies
# COPY package.json /usr/src/app/
# clone statsd repo to folder "statsd", in statsd to npm install appinsights-statsd from up-level folder
RUN git clone https://github.com/statsd/statsd.git
RUN cd appinsights-statsd\
    && npm install\
    && cd /usr/src/app/statsd\
    && npm install /usr/src/app/appinsights-statsd\
    && npm install\
    && npm cache clean --force\
    && echo "\
    {\n\
        backends: ['appinsights-statsd'], \n\
        aiInstrumentationKey: process.env.APPLICATION_INSIGHTS_INSTRUMENTATION_KEY,\n\ 
        aiPrefix: 'airflow2', \n\
        aiTrackStatsDMetrics: true,\n\
        log:{\n\
            backend: 'syslog'\n\
        }\n\
    } "\
    >> ./config.js

RUN cp -r ./statsd/node_modules/appinsights-statsd/node_modules/* ./statsd/node_modules/
USER root
RUN apt-get update && apt-get install -y --only-upgrade libdjvulibre21=3.5.27.1-10+deb10u1 \
        libpq-dev=11.14-0+deb10u1 \
        libpq5=11.14-0+deb10u1 \
        libicu63=63.1-6+deb10u2 \
        libtiff-dev=4.1.0+git191117-2~deb10u3 \
        libtiffxx5=4.1.0+git191117-2~deb10u3 \
        libtiff5=4.1.0+git191117-2~deb10u3
# Expose required ports
EXPOSE 8125/udp
EXPOSE 8126

# Start statsd with application insights backend
ENTRYPOINT [ "node", "statsd/stats.js", "statsd/config.js" ]
