cat > local.yaml <<LOCALRUN
AZURE_TENANT_ID: "${TENANT_ID}"
AZURE_CLIENT_ID: "${ENV_PRINCIPAL_ID}"
AZURE_CLIENT_SECRET: "${ENV_PRINCIPAL_SECRET}"
KEYVAULT_URI: "${ENV_KEYVAULT}"
aad_client_id: "${ENV_APP_ID}"
appinsights_key: "${ENV_APPINSIGHTS_KEY}"
cosmosdb_account: "${ENV_COSMOSDB_HOST}"
cosmosdb_database: "${COSMOS_DB_NAME}"
cosmosdb_key: "${ENV_COSMOSDB_KEY}"
entitlements_app_key: "${API_KEY}"
entitlements_service_api_key: "${API_KEY}"
entitlements_service_endpoint: "http://${ENV_HOST}/entitlements/v1"
legal_service_endpoint: "http://${ENV_HOST}/api/legal/v1"
legal_service_region: "${ENV_REGION}"
search_service_endpoint: "http://${ENV_HOST}/api/search/v2/query"
servicebus_namespace_name: "${ENV_SERVICEBUS_NAMESPACE}"
servicebus_connection_string: "${ENV_SERVICEBUS_CONNECTION}"
servicebus_topic_name: "${RECORD_SERVICE_BUS_TOPIC}"
storage_account: "${ENV_STORAGE}"
storage_account_key: "${ENV_STORAGE_KEY}"
server_port: "${server_port}"
LOCALRUN

cat > test/local.yaml <<LOCALTEST
STORAGE_URL: "http://localhost:${server_port}/api/storage/v2/"
LEGAL_URL: "http://${ENV_HOST}/api/legal/v1/"
TENANT_NAME: "${OSDU_TENANT}"
AZURE_AD_TENANT_ID: "${TENANT_ID}"
INTEGRATION_TESTER: "${ENV_PRINCIPAL_ID}"
TESTER_SERVICEPRINCIPAL_SECRET: "${ENV_PRINCIPAL_SECRET}"
AZURE_STORAGE_ACCOUNT: "${ENV_STORAGE}"
AZURE_AD_APP_RESOURCE_ID: "${ENV_APP_ID}"
NO_DATA_ACCESS_TESTER: "${NO_ACCESS_ID}"
NO_DATA_ACCESS_TESTER_SERVICEPRINCIPAL_SECRET: "${NO_ACCESS_SECRET}"
DOMAIN: "${COMPANY_DOMAIN}"
PUBSUB_TOKEN: "az"
DEPLOY_ENV: "empty"
LOCALTEST

cat > test/hosted.yaml <<DEVTEST
STORAGE_URL: "http://${ENV_HOST}/api/storage/v2/"
LEGAL_URL: "http://${ENV_HOST}/api/legal/v1/"
TENANT_NAME: "${OSDU_TENANT}"
AZURE_AD_TENANT_ID: "${TENANT_ID}"
INTEGRATION_TESTER: "${ENV_PRINCIPAL_ID}"
TESTER_SERVICEPRINCIPAL_SECRET: "${ENV_PRINCIPAL_SECRET}"
AZURE_STORAGE_ACCOUNT: "${ENV_STORAGE}"
AZURE_AD_APP_RESOURCE_ID: "${ENV_APP_ID}"
NO_DATA_ACCESS_TESTER: "${NO_ACCESS_ID}"
NO_DATA_ACCESS_TESTER_SERVICEPRINCIPAL_SECRET: "${NO_ACCESS_SECRET}"
DOMAIN: "${COMPANY_DOMAIN}"
PUBSUB_TOKEN: "az"
DEPLOY_ENV: "empty"
DEVTEST
