# This file contains the essential configs for the osdu on azure helm chart
global:

  isDataPartitionDeployment: true

  # Service(s) Replica Count
  replicaCount: 2

  ################################################################################
  # Specify the azure environment specific values
  #
  azure:
    tenant: #{tenant-id}#
    subscription: #{subscription-id}#
    resourcegroup: #{base-name-cr}#-rg
    identity: #{base-name-cr}#-osdu-identity
    identity_id: #{osdu-identity-id}#
    keyvault: #{base-name-cr}#-kv
    appid: #{aad-client-id}#

    dp:
      tenant: #{data-partition-tenant-id}#
      subscription: #{data-partition-subscription-id}#
      resourcegroup: #{base-name-dp}#-rg
      identity: #{base-name-dp}#-osdu-identity
      identity_id: #{management-identity-id}#
      keyvault: #{base-name-dp}#-kv

  ################################################################################
  # Specify the Ingress Settings
  # DNS Hostname for thet Gateway
  # Admin Email Address to be notified for SSL expirations
  # Lets Encrypt SSL Server
  #     https://acme-staging-v02.api.letsencrypt.org/directory  --> Staging Server
  #     https://acme-v02.api.letsencrypt.org/directory --> Production Server
  #
  ingress:
    hostname: #{AIRFLOW_DNS_HOST}#
    admin: #{ADMIN_EMAIL}#
    sslServer: https://acme-v02.api.letsencrypt.org/directory  # Production
    enableKeyvaultCert: #{DP_ENABLE_KEYVAULT_CERT}#                     

  ################################################################################
  # Specify the istio specific values
  # based64 encoded username and password
  #
  istio:
    username: #{istio-username}#
    password: #{istio-password}#
    dns_host: #{AIRFLOW_DNS_HOST}#

  ################################################################################
  # Specify the resource limits
  #
  resourceLimits:
    defaultCpuRequests: "0.5"
    defaultMemoryRequests: "4Gi"
    defaultCpuLimits: "1"
    defaultMemoryLimits: "4Gi"