cat > local.yaml <<LOCALRUN
AZURE_TENANT_ID: "${TENANT_ID}"
AZURE_CLIENT_ID: "${ENV_PRINCIPAL_ID}"
AZURE_CLIENT_SECRET: "${ENV_PRINCIPAL_SECRET}"
KEYVAULT_URI: "${ENV_KEYVAULT}"
aad_client_id: "${ENV_APP_ID}"
appinsights_key: "${ENV_APPINSIGHTS_KEY}"
cosmosdb_account: "${ENV_COSMOSDB_HOST}"
cosmosdb_database: "${COSMOS_DB_NAME}"
cosmosdb_key: "${ENV_COSMOSDB_KEY}"
entitlements_service_endpoint: "https://${ENV_HOST}/entitlements/v1/"
entitlements_app_key: "${API_KEY}"
entitlements_service_api_key: "${API_KEY}"
servicebus_namespace_name: "${ENV_SERVICEBUS_NAMESPACE}"
servicebus_connection_string: "${ENV_SERVICEBUS_CONNECTION}"
servicebus_topic_name: "${RECORD_SERVICE_BUS_TOPIC}"
storage_service_url: "https://${ENV_HOST}/api/storage/v2/"
STORAGE_SCHEMA_HOST: "https://${ENV_HOST}/api/storage/v2/schemas"
STORAGE_QUERY_RECORD_HOST: "https://${ENV_HOST}/api/storage/v2/records"
STORAGE_QUERY_RECORD_FOR_CONVERSION_HOST: "https://${ENV_HOST}/api/storage/v2/query/records:batch"
server_port: "${server_port}"
LOCALRUN


cat > test/hosted.yaml <<DEVTEST
AZURE_AD_TENANT_ID: "${TENANT_ID}"
INTEGRATION_TESTER: "${ENV_PRINCIPAL_ID}"
AZURE_TESTER_SERVICEPRINCIPAL_SECRET: "${ENV_PRINCIPAL_SECRET}"
AZURE_AD_APP_RESOURCE_ID: "${ENV_APP_ID}"
aad_client_id: "${ENV_APP_ID}"
STORAGE_HOST: "https://${ENV_HOST}/api/storage/v2/"
ELASTIC_HOST: "${ENV_ELASTIC_HOST}"
ELASTIC_PORT: "${ENV_ELASTIC_PORT}"
ELASTIC_USER_NAME: "${ENV_ELASTIC_USERNAME}"
ELASTIC_PASSWORD: "${ENV_ELASTIC_PASSWORD}"
DEFAULT_DATA_PARTITION_ID_TENANT1: "${OSDU_TENANT}"
DEFAULT_DATA_PARTITION_ID_TENANT2: "${OSDU_TENANT2}"
ENTITLEMENTS_DOMAIN: "${COMPANY_DOMAIN}"
ENVIRONMENT: "CLOUD"
LEGAL_TAG: "opendes-public-usa-dataset-7643990"
OTHER_RELEVANT_DATA_COUNTRIES: "US"
DEVTEST
