{{- $isEnabled := .Values.airflow.isDataPartitionDeployment | default false -}}
{{- $prefixNamespaceString := printf "%s-" .Release.Namespace }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $isEnabled | ternary $prefixNamespaceString "" }}airflowdagpv1
  labels:
    usage: {{ $isEnabled | ternary $prefixNamespaceString "" }}airflowtwo-dag
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadOnlyMany
  azureFile:
    secretName: airflow
    shareName: airflow2dags
  volumeMode: Filesystem
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowdagpvc1
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 6Gi
  selector:
    matchLabels:
      usage: {{ $isEnabled | ternary $prefixNamespaceString "" }}airflowtwo-dag