apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: osdu-airflow2-identity
spec:
  type: 0
  resourceID: "/subscriptions/{{ .Values.azure.subscription }}/resourcegroups/{{ .Values.azure.resourcegroup }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ .Values.azure.identity }}"
  clientID: "{{ .Values.azure.identity_id }}"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: osdu-airflow2-identity-binding
spec:
  azureIdentity: osdu-airflow2-identity
  selector: osdu-airflow2-identity
