#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
{{ $isDataPartition := .Values.airflow.isDataPartitionDeployment | default false }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-airflow
spec:
  provider: azure
  secretObjects:
{{ if not $isDataPartition }}
  - secretName: active-directory
    type: Opaque
    data:
    - objectName: "app-dev-sp-tenant-id"
      key: tenantid
    - objectName: "aad-client-id"
      key: application-appid
    - objectName: "app-dev-sp-username"
      key: principal-clientid
    - objectName: "app-dev-sp-password"
      key: principal-clientpassword
    - objectName: "app-dev-sp-id"
      key: principal-objectid      
  - secretName: central-logging
    type: Opaque
    data:
    - objectName: "appinsights-key"
      key: appinsights
    - objectName: "log-workspace-id"
      key: workspace-id
    - objectName: "log-workspace-key"
      key: workspace-key
  - secretName: storage
    type: Opaque
    data:
    - objectName: "opendes-storage"
      key: storage-account
    - objectName: "opendes-storage-key"
      key: storage-key
  - secretName: cosmos
    type: Opaque
    data:
    - objectName: "opendes-cosmos-endpoint"
      key: cosmos-endpoint
    - objectName: "opendes-cosmos-connection"
      key: cosmos-connection
    - objectName: "opendes-cosmos-primary-key"
      key: cosmos-primary-key
  - secretName: servicebus
    type: Opaque
    data:
    - objectName: "opendes-sb-namespace"
      key: servicebus-namespace
    - objectName: "opendes-sb-connection"
      key: servicebus-connection
  - secretName: elastic
    type: Opaque
    data:
    - objectName: "opendes-elastic-endpoint"
      key: elastic-endpoint
    - objectName: "opendes-elastic-username"
      key: elastic-username
    - objectName: "opendes-elastic-password"
      key: elastic-password
{{ else }}
  - secretName: dp-logging
    type: Opaque
    data:
    - objectName: "log-workspace-id"
      key: workspace-id
    - objectName: "log-workspace-key"
      key: workspace-key
{{ end }}
  - secretName: airflow
    type: Opaque
    data:
    - objectName: airflow-storage
      key: storage-account
    - objectName: airflow-storage-key
      key: storage-key
    - objectName: airflow-storage-connection
      key: storage-connection
    - objectName: airflow-remote-log-connection
      key: remote-log-connection
    - objectName: airflow-admin-password
      key: admin-password
    - objectName: airflow-fernet-key
      key: fernet-key
    - objectName: airflow-storage
      key: azurestorageaccountname
    - objectName: airflow-storage-key
      key: azurestorageaccountkey  
  - secretName: postgres
    type: Opaque
    data:
    - objectName: "postgres-password"
      key: postgres-password
  - secretName: redis
    type: Opaque
    data:
    - objectName: "redis-queue-password"
      key: redis-queue-password
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    resourceGroup: "{{ .Values.azure.resourcegroup }}"
    keyvaultName: "{{ .Values.azure.keyvault }}"
    subscriptionId: "{{ .Values.azure.subscription }}"
    tenantId: "{{ .Values.azure.tenant }}"
{{ if $isDataPartition }}
    objects: |      
      array:
        - |
          objectName: log-workspace-id
          objectType: secret
        - |
          objectName: log-workspace-key
          objectType: secret
        - |
          objectName: airflow-storage
          objectType: secret
        - |
          objectName: airflow-storage-key
          objectType: secret
        - |
          objectName: airflow-storage-connection
          objectType: secret
        - |
          objectName: airflow-remote-log-connection
          objectType: secret
        - |
          objectName: airflow-admin-password
          objectType: secret
        - |
          objectName: airflow-fernet-key
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: redis-queue-password
          objectType: secret
{{ else }}
    objects: |
      array:
        - |
          objectName: app-dev-sp-tenant-id
          objectType: secret
        - |
          objectName: aad-client-id
          objectType: secret
        - |
          objectName: appinsights-key
          objectType: secret
        - |
          objectName: app-dev-sp-username
          objectType: secret
        - |
          objectName: app-dev-sp-password
          objectType: secret
        - |
          objectName: app-dev-sp-id
          objectType: secret
        - |
          objectName: opendes-storage
          objectType: secret
        - |
          objectName: opendes-storage-key
          objectType: secret
        - |
          objectName: opendes-cosmos-endpoint
          objectType: secret
        - |
          objectName: opendes-cosmos-connection
          objectType: secret
        - |
          objectName: opendes-cosmos-primary-key
          objectType: secret
        - |
          objectName: opendes-sb-namespace
          objectType: secret
        - |
          objectName: opendes-sb-connection
          objectType: secret
        - |
          objectName: airflow-storage
          objectType: secret
        - |
          objectName: airflow-storage-connection
          objectType: secret
        - |
          objectName: airflow-remote-log-connection
          objectType: secret
        - |
          objectName: airflow-storage-key
          objectType: secret
        - |
          objectName: airflow-admin-password
          objectType: secret
        - |
          objectName: airflow-fernet-key
          objectType: secret
        - |
          objectName: opendes-elastic-endpoint
          objectType: secret
        - |
          objectName: opendes-elastic-username
          objectType: secret
        - |
          objectName: opendes-elastic-password
          objectType: secret
        - |
          objectName: log-workspace-id
          objectType: secret
        - |
          objectName: log-workspace-key
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: redis-queue-password
          objectType: secret
{{ end }}