{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: airflow-pgbouncer
  labels:
    tier: airflow
    component: pgbouncer
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: pgbouncer
    release: {{ .Release.Name }}
  ports:
    - name: pgbouncer
      protocol: TCP
      port: {{ .Values.pgbouncer.port }}
      targetPort: {{ .Values.pgbouncer.port }}
{{- end }}